#!/usr/bin/env python3
"""Run the complete bounded campaign sequentially with one worker.

The one-command driver executes phases in one bounded Python process. Every
phase remains separately runnable through experiment.py for resumable hosts.
A fresh output directory is mandatory; retained evidence is never overwritten.
"""
from __future__ import annotations

import argparse
import resource
import time
from pathlib import Path

from pccfr.campaign import PHASES
from pccfr.provenance import binding_id, input_summary, object_summary, scientific_source_summary
from pccfr.repair_checks import build_repair_report
from pccfr.util import measure, read_json, write_json

ORDER = list(PHASES)


def _apply_limits() -> None:
    address = 3_500 * 1024 * 1024
    resource.setrlimit(resource.RLIMIT_AS, (address, address))
    resource.setrlimit(resource.RLIMIT_CPU, (1800, 1800))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    _apply_limits()
    if args.out.exists() or args.out.is_symlink():
        raise SystemExit(f"refusing to overwrite existing output directory: {args.out}")
    args.out.mkdir(parents=True, exist_ok=False)

    start_wall = time.monotonic()
    start_cpu = time.process_time()
    summaries = []
    for phase in ORDER:
        result = measure(lambda selected=phase: PHASES[selected](args.out))
        write_json(args.out / f"{phase}.json", result)
        print(args.out / f"{phase}.json", flush=True)
        summaries.append(result)

    artifact_root = Path(__file__).resolve().parent
    source = scientific_source_summary(artifact_root)
    inputs = input_summary(args.out / "inputs")
    objects = object_summary(args.out / "objects")
    binding = binding_id(source, inputs)
    provenance = {
        "binding_id": binding,
        "source_summary": source,
        "input_summary": inputs,
        "object_summary": objects,
        "interpretation": (
            "Aggregate binding of the scientific source and exact generated input tables. "
            "It is regenerated by the campaign; retained JSON is not hand-edited."
        ),
    }
    write_json(args.out / "provenance.json", provenance)

    # Bind every phase result to the same source/input snapshot after all inputs
    # have been written. Resource fields remain measured phase data.
    for phase in ORDER:
        path = args.out / f"{phase}.json"
        result = read_json(path)
        result["binding_id"] = binding
        write_json(path, result)

    mismatches = sum(int(value.get("mismatches", 0)) for value in summaries)
    summary = {
        "phases": len(summaries),
        "phase_order": ORDER,
        "mismatches": mismatches,
        "binding_id": binding,
        "provenance_file": "provenance.json",
        "cumulative_cpu_seconds": sum(float(value["resource"]["cpu_seconds"]) for value in summaries),
        "maximum_process_peak_rss_kib": max(int(value["resource"]["peak_rss_kib"]) for value in summaries),
        "workers": 1,
        "driver_and_child_cpu_seconds": time.process_time() - start_cpu,
        "driver_wall_seconds": time.monotonic() - start_wall,
    }
    write_json(args.out / "summary.json", summary)
    repair = build_repair_report(artifact_root, args.out, binding)
    write_json(args.out / "repair-validation.json", repair)
    return 0 if mismatches == 0 and repair["accepted"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
